


makan = input("apakah kamu sudah makan:")
tidak = 15 
if makan == "tidak":
    print("")
elif makan == "ya" and ("waktu makan > 15").lower:
    print("")
else:
    print("sebaiknya anda segera makan")



mandi = input("apakah kamu sudah mandi:")
tidak = 10
if mandi == "tidak":
    print("")
elif mandi == "ya" and ("waktu mandi > 10").lower:
    print("")
else:
    print("sebaiknya anda segera mandi")


berangkat = (input("menggunakan apa anda berangkat:"))
jalan_kaki = 30 #menit
pakai_motor = 15 #menit
if berangkat == "jalan_kaki":
    print("anda membutuhkan waktu 30 menit untuk sampai ke kampus")
elif berangkat == "pakai_motor":
    print("anda memerlukan waktu 15 menit untuk sampai ke kampus")








