# # Perintah If
# nama = "alpro"

# if nama == "alpro":
#     print("ini matukul", nama)

# # Perintah If Else
# angka = 7

# if angka > 7:
#     print("angka besar")

# else :
#     print("angka kecil")


# # Perintah If Elif Else
# nilai = 70

# if nilai < 40:
#     print("remidi")

# elif nilai < 70:
#     print("Rata rata")

# elif nilai < 100:
#     print("lulus")

# else :
#     print("tidak lulus")

# Perintah If Bersarang
angka = 12
hasil = "Genap" if angka % 2 == 0 else "Ganjil"
print(hasil)